### ISSUE TITLE
Expose 'Splash' and make it overridable

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-client#110]
From https://community.os-js.org/t/customise-loading-box-on-login/433/3

> hi i want to replace the ‘loading…’ message on startup with something else, is there a way to do this?

**Comment by andersevenrud** [comment]
This was published

**Comment by andersevenrud** [comment]
Documented here: https://manual.os-js.org/v3/guide/visuals/#splash-screen

**Comment by 17lwinn** [comment]
thanks that would help a lot

**Comment by andersevenrud** [comment]
Great :)
