### ISSUE TITLE
Configuration option to override window defaults in applications

### ISSUE THREAD

**Issue by elixx** [os-js/osjs-client#115]
It would be nice to, for example, be able to customize the window size of the Xterm application.

We may have chatted about this ;)
Ref: https://gitter.im/os-js/OS.js?at=5ed17522225dc25f54b450ed

**Comment by andersevenrud** [comment]
I started messing around with some other stuff, and bedtime suddenly turned into codetime :joy: 

So, I opened a PR that implements this. I'll give it a few more hands on tests before merging, but I'm pretty confident that my unit tests covers it al (if you ignore the failed checks in the PR that is... seems like I have to update some deps for Github Actions to pass).

If you're feeling adventorius you could always try to switch out `@osjs/client` in your distro with a local branch of these changes ;)

**Comment by andersevenrud** [comment]
Note: The option schema is a bit diffrent than we discussed, but it you inspect the commit, you should see an example in the `config.js` file.

**Comment by andersevenrud** [comment]
Just a small side-note for these changes. If you reload a session (restore application state), this will not take effect.

If Xterm windows was restored, you'll have to close all windows, then launch the application again, and it should work :)

**Comment by andersevenrud** [comment]
I just released a new version of `@osjs/client` with these changes :)
