### ISSUE TITLE
Change position of application window by desktop resizing

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#135]
Hi
I am developing an application in Osjs.
I need the window position to be changed by resizing the desktop. Currently position of all windows remained fixed as the desktop resizes.

**Comment by andersevenrud** [comment]
> I need the window position to be changed by resizing the desktop

Reading this, I'm not sure if you want to make **all** windows clamp to the viewport or just the one you're developing.

There's a method called `win.clampToViewport()` that does exactly what you need, that can be used for this purpose. I can add it so this is automatically called when the viewport is resized for all windows.

**Comment by mahsashadi** [comment]
I need to have this functionality for **applications** and also for developed **widgets**.

**Comment by andersevenrud** [comment]
Going to assume you meant windows there. OK, I'll look into this.

**Comment by andersevenrud** [comment]
Could you open an issue in osjs-widgets about this as well ? I cannot implement that behavior in this repo.

**Comment by andersevenrud** [comment]
PR: https://github.com/os-js/osjs-client/pull/136

**Comment by andersevenrud** [comment]
I've published osjs-client `3.2.0` which contains this change and is enabled by default.

Let me know how it works out :)

**Comment by mahsashadi** [comment]
Thank you, now it works as I need :)

**Comment by andersevenrud** [comment]
Great!
