### ISSUE TITLE
mapping applications to user groups

### ISSUE THREAD

**Issue by dsikes** [os-js/osjs-client#140]
For my particular use case I will have multiple users logging into the system.
Depending on which groups the user belongs to, this should control which applications they see / can launch.

@andersevenrud mentioned that its currently supported via metadata.json here:
https://github.com/os-js/osjs-client/blob/master/src/packages.js#L414

But we would like to extend it for this specific use case.

**Comment by andersevenrud** [comment]
Great suggestion. On it!

**Comment by andersevenrud** [comment]
I opened a PR for this: https://github.com/os-js/osjs-client/pull/141

Now, this only hides the packages visually. But I can make it so they are blocked entirely from being launched if that's something you need :)

**Comment by dsikes** [comment]
I'm not sure my users would try to launch anything they couldn't see - but, it does seem like a good solution just to cover our bases. But this totally rocks!

**Comment by andersevenrud** [comment]
Alright. I'll knock that one out as well because I know others have wondered about this as well :)

**Comment by andersevenrud** [comment]
I just published `@osjs/client@3.4.0` with all the changes mentioned :)

**Comment by andersevenrud** [comment]
I have now documented all of the options for disabling packages here: https://manual.os-js.org/guide/disabling-packages/
