### ISSUE TITLE
Dragover event intercepted preventing further propagation 

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-client#148]
I am unable to use the ondragover handler on any elements within osjs. During my dragover, the `inside` variable below is always true and the early return is never hit, so the ondrag isn't propagated down to my lonely, sad little handler :worried:

[dnd.js: 222](https://github.com/os-js/osjs-client/blob/6512debfd4e98f8536b2100e86b346ad99803dfe/src/utils/dnd.js#L222)
```
  const dragover = ev => {
    ev.preventDefault();

    const inside = el.contains(ev.target);

    if (!inside) {
      el.classList.remove('osjs__drop');
      return false;
    }

    ev.stopPropagation();
```

**Comment by josephjeno** [comment]
By the way, `drop`, `dragstart`, `dragend`.. all work just fine. `dragover` is the only one I'm having issues with.

**Comment by andersevenrud** [comment]
Found the commit where we worked around another similar issue: https://github.com/os-js/osjs-client/commit/5c166ab04ae3438f91101ab671da6800a42ed87e

**Comment by andersevenrud** [comment]
Could you provide a minimal example on how to reproduce this issue ?

**Comment by josephjeno** [comment]
Actually, I can't, because I haven't been able to replicate the issue with the minimal example. 🤦

**Comment by josephjeno** [comment]
I'll pick it back up tomorrow and probably close my issue. Sorry man. Something is intercepting my handler, that's for sure...

**Comment by andersevenrud** [comment]
You figured it out ? :thinking:

**Comment by josephjeno** [comment]
I've surrendered for now, but since I can't reproduce it outside of my environment, I'm fairly sure osjs isn't the issue.

I had a breakpoint on the dragover event, which hit the osjs dnd.js file and then disappeared into the void, which is why I had it pegged as osjs.  I suppose the next step is removing that piece of code and going from there, but that will have to wait for now. 

One thing's for sure, debugging these is a total... drag heh.

**Comment by andersevenrud** [comment]
I see. Did you get any clues as to which element the event was triggered on ? That would pretty much explain if it's os.js or not immediately :)
