### ISSUE TITLE
Support SVG assets

### ISSUE THREAD

**Issue by yutyo** [os-js/osjs-client#150]
Supporting svg files in themes and adjusting them to the right size by pre-defined sizes in a global css would be nice.

**Comment by andersevenrud** [comment]
Indeed.

---

From Gitter conversation:

Technically any image type is supported and the fallback is .png extension. However, the icon theme service is not currently "extension aware", so it will always favor pngs. I haven't gotten around to implementing that yet. There's two ways to solve this:

1. Add a property in the metadata that identifies all icons as either svg or png
2. Or have a property thats a key-value pair with the icon name and the extension
3. 
And then have the icon theme service pick the approriate extension based on that.

**Comment by ajmeese7** [comment]
I just ran into this same issue implementing a new icon theme, I'm going to work on a fix. Not sure if there's a pretty way to do it or if it'll have to be "hacky", but I'll come up with something and make a PR.
