### ISSUE TITLE
Swedish not available on demo site.

### ISSUE THREAD

**Issue by Malte0621** [os-js/osjs-client#152]
Swedish isn't available on the demo site.. I don't know if it is a bug, or if you haven't added it to the demo site..
![image](https://user-images.githubusercontent.com/50240920/113265018-f28cca80-92d3-11eb-9cb8-ad2d6e6f15d5.png)

**Comment by Malte0621** [comment]
Ill use my own server for now.. (no need to hurry.)

**Comment by andersevenrud** [comment]
Demo site is a few versions behind master

**Comment by andersevenrud** [comment]
Should be up to date now
