### ISSUE TITLE
Drag and drop warning in application window

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#153]
Hello. I am trying to make available drag and drop option for user in my application window, in below code:

```js
import React from 'react';
export default function App ({win, proc}) {
  //const [basic] = React.useState(() => core.make('osjs/basic-application', proc, win));
  React.useEffect(() => {
    win.on('drop', (_, draggedData) => console.log('drag and drop happened'));
    // win.on('drop', (_, draggedData) => basic.open(draggedData));
  }, []);

    return (
      <p> test </p>
    );
}
```
But It does not work due to the following warning. Do you know what is the problem? (I am using the latest versions of packages)

![Screenshot from 2021-04-17 14-42-20](https://user-images.githubusercontent.com/70196035/115109724-bd979d80-9f8c-11eb-9148-a1d42b1cdb41.png)

**Comment by andersevenrud** [comment]
What's the data of the drop?

**Comment by mahsashadi** [comment]
A file for scanning (txt, png, exe, ...)

**Comment by andersevenrud** [comment]
As in, from the file manager ?

**Comment by mahsashadi** [comment]
Oops! Sorry. We only can drag and drop from file manager files by this code. I was trying files from my system.
Thanks a lot!
