### ISSUE TITLE
ENOENT error on .desktop/.shortcuts.json when there are no desktop shortcuts

### ISSUE THREAD

**Issue by valp124** [os-js/osjs-client#170]
On every page load, I get an error, both on the server and the client, that `.desktop/.shortcuts.json` file is not found. Indeed, it's not there -- I have actual files in my `.desktop` directory, but not _shortcuts_ per se. E.g.:

![image](https://user-images.githubusercontent.com/7969539/140777519-6ac9460e-ba39-4907-8c00-e95bc8f384e7.png)

This is completely benign, of course, but I thought I'd mention it anyway 😊

**Comment by andersevenrud** [comment]
Yeah, these come from the VFS error handler that catches adapter exceptions and dumps them to the console.

In this case it probably shouldn't happen :slightly_smiling_face:
