### ISSUE TITLE
`parseMontpointPrefix` Question

### ISSUE THREAD

**Issue by ajmeese7** [os-js/osjs-client#174]
Is this function supposed to be `parseMountpointPrefix`? I went ahead and replaced all 16 instances in my fork, but I don't want to open a PR if you named it that way for a reason

**Comment by andersevenrud** [comment]
Just a small typo :)

**Comment by ajmeese7** [comment]
Gotcha, do you want me to push a fix?

**Comment by andersevenrud** [comment]
Sure! Feel free to open up PR-s on any of your findings. I don't have much time to work on this project as of late, so any contribution is most welcome!
