### ISSUE TITLE
App visibility in panel tray  only when minimzed?

### ISSUE THREAD

**Issue by mikeblackstock** [os-js/osjs-client#177]
My os-js project [screencap attached] presents the user with a number of apps 'tiled'
on the screen, at startup, and clicking on their iicons in the panel tray evidently does nothing. 
This seems to confuse new users, who expect something to happen when they click on
webpage links.

Is their a way to make apps appear in the panel tray *only* when they've been minimized?
I've gone through all the docs, and I can't find a visibility attribute other than 'restricted/global'.

thx for any advice!

![osjs-omet](https://user-images.githubusercontent.com/223399/163456255-8c5a852f-75fa-437a-8146-aeff1691a11f.png)

**Comment by andersevenrud** [comment]
Made a patch for you on this.

If you update `@osjs/panels` and then add this to your `src/client/index.scss` and rebuild, you should be able to make this work.

```
.osjs-panel-item[data-name="windows] div[data-minimized="false"] {
  display: none;
}
```

**Comment by mikeblackstock** [comment]
Fantastic, Anders. Works perfectly: a few additional apps can be started minimized and
they'll stand out in the panel tray at start-up.

PS - small typo, in case anyone else is following: there should be a double quote after 
data-name="windows:  [data-name="windows"]
Thx so much!

-M.
