### ISSUE TITLE
[Request] Different Window Managers

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-client#19]
It would be cool if the window manager was a package that would be installed so if someone wanted a different window manager, they just change some settings and the new window manager is the applied.

**Comment by andersevenrud** [comment]
You can replace all behavior via a custom `WindowBehavior` class and service providers.

**Comment by SpaceboyRoss01** [comment]
There needs to be some documentation on that then.

**Comment by andersevenrud** [comment]
This is the class that spesifices all events, etc:

https://github.com/os-js/osjs-client/blob/master/src/window-behavior.js

And for the rest of the features, it's a matter of replacing the `DesktopServiceProvider` (or just customize it),

If the custom window manager requires special themes, these can be provided via special packages.

> There needs to be some documentation on that then.

Feel free to create an issue on this here:

https://github.com/os-js/manual.os-js.org

**Comment by andersevenrud** [comment]
> And for the rest of the features, it's a matter of replacing the DesktopServiceProvider (or just customize it),

Same goes for `PanelServiceProvider` if that requires another implementation.

**Comment by andersevenrud** [comment]
> This is the class that spesifices all events, etc:

I forgot to mention that windows can have their own templates as well:

https://github.com/os-js/osjs-client/blob/master/src/window.js#L203

Though this currently does not have a global setting. I'll add that.
