### ISSUE TITLE
Customize the style of active osjs window

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#195]
In osjs there is a feature that only keeps one window active. The other opened windows will get `false` focus mode.
How can I change this feature, for example only change the window header color of active one?

**Comment by andersevenrud** [comment]
Not currently. But good news. @ajmeese7 has implemented this, so maybe he can put up a PR ? :blush:

**Comment by andersevenrud** [comment]
Oh, I think I might have misunderstood you. 

All windows have a DOM attribute for their state. I.e.: `data-focused="true"` and `data-focused="false"`. You can use this in your CSS to apply custom styles.

**Comment by andersevenrud** [comment]
I'm pretty sure I gave the solution in previous comment. Closing.

Feel free to re-open if this doesn't work for you.
