### ISSUE TITLE
get package from gitlab not just github

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-client#2]
currently, I have to manually git clone the **git repo** and run the **npm i** command. 

Would be nice if the same `npm run install:package -- https://github.com/os-js/osjs-example-application.git` would work on a gitlab repo as well.

**Comment by andersevenrud** [comment]
I was thinking about this not long ago and I think I have a proper solution for this.

Moving the issue over to `@osjs/cli`: https://github.com/os-js/osjs-cli/issues/1
