### ISSUE TITLE
Omitting Home path from client

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-client#210]
Hello

we are searching for a way to omit `osjs` and home `mountpoints` from client, but it leads to error since we don't have any other mountpoint to set as `defaultPath`.

We have other mounpoint, but its name is known at run time (We only know that it ends with `Drive`)

```
 //src/client/index.js

  const foundMount = osjs.configuration.vfs.mountpoints.find((mount) => mount.name === 'osjs');
  if (foundMount) {
    foundMount.enabled = false;
  }

  const foundMount1 = osjs.configuration.vfs.mountpoints.find((mount) => mount.name === 'home');
  if (foundMount1) {
    foundMount1.enabled = false;
  }
```

```
//src/client/config.js

vfs: {
  defaultPath: '', 
  }
```
![Screenshot from 2024-01-02 18-11-39](https://github.com/os-js/osjs-client/assets/70196035/f470f138-68ea-4a0d-9e66-1ff8011ac71d)

what is the solution? @andersevenrud

**Comment by andersevenrud** [comment]
Set the default to the application mountpoint, then try setting the configuration on run-time.

```
// Somewhere in your service
core.configuration.vfs.defaultPath = yourResolvedMountpoint;
```

**Comment by maryam4s26** [comment]
hi thanks a lot
As you said, I have made the following settings in the `src/client/config.js`  and it worked correctly.
```
  vfs: {
    defaultPath: 'apps:/',
  }
```
Also according to what you said, I was able to dynamically set the default value in the client side provider service.

**Comment by andersevenrud** [comment]
Great!

Please close the issues you create when a solution has been produced.
