### ISSUE TITLE
Restrictions on mountpoint naming

### ISSUE THREAD

**Issue by maryam4s26** [os-js/osjs-client#211]
Hi @andersevenrud 
Why is there a dot ('.') limitation in naming a mountpoint?
https://github.com/os-js/osjs-client/commit/79046faecc82082ba6d56c2649626a95b951001b

**Comment by andersevenrud** [comment]
I cannot remember my reasoning behind this character limitation.

... maybe because of parsing, and that `.` usually is a special character that denotes either an extension or like `.` or `..` on a filesystem 🤷‍♂️
