### ISSUE TITLE
Alert message display is not the same in different browsers

### ISSUE THREAD

**Issue by maryam4s26** [os-js/osjs-client#212]
Hi @andersevenrud.
I have an error in the server, but the Alert message display is not the same in different browsers.

Error in server:
![image](https://github.com/os-js/osjs-client/assets/65979871/3db8659d-f672-4250-ac9a-4778b812dbf1)

in google chrome:
![image](https://github.com/os-js/osjs-client/assets/65979871/fde17cc9-9b1e-4c97-a50e-05c0ab6a0e2c)

in firefox:
![image](https://github.com/os-js/osjs-client/assets/65979871/8029430a-c21c-42bb-b75b-5aafc8b0ac37)

in Microsoft Edge 
![image_2024_01_08T19_32_14_780Z](https://github.com/os-js/osjs-client/assets/65979871/7cb34231-0e1b-432d-addb-38394947b6d9)

in safari:
![image](https://github.com/os-js/osjs-client/assets/65979871/7d32f469-e3fa-4867-8484-6dfc74580715)

**Comment by andersevenrud** [comment]
The actual stack could vary between browser engines depending on how they read the sourcemaps, however this should not affect the actual error message.

So this must be a problem with how the dialog builds the displayed error:

https://github.com/os-js/osjs-dialogs/blob/bf88b9300fbe7fbc268748041a7e9306bc173a28/src/dialogs/alert.js#L85-L92

This maybe should display `error.message` in addition to `error.stack` directly.

**Comment by andersevenrud** [comment]
If you're up for a small quest, feel free to look into this one and submit a PR :)

**Comment by maryam4s26** [comment]
Sure. thank you :D

**Comment by andersevenrud** [comment]
This was fixed and released with `@osjs/dialogs@3.2.2`
