### ISSUE TITLE
Widget settings in config

### ISSUE THREAD

**Issue by maryam4s26** [os-js/osjs-client#215]
Hi @andersevenrud 
If possible, what is the widget parameter in the config file for?  https://github.com/os-js/osjs-client/blob/master/src/config.js#L214

**Comment by andersevenrud** [comment]
That would be:

```
{
  name: string;
  options: {};
}[];
```

Where `options` for example in the digtal clock is `{fontColor: string; fontFamily: string}`.

**Comment by maryam4s26** [comment]
thank you
