### ISSUE TITLE
Some menu fixes

### ISSUE THREAD

**Issue by filips123** [os-js/osjs-client#24]
There should be some menu fixes in v3.

Menu should be using a little different color to be separated with top panel. They are currently both black so it it not possible to separate them.  This is also problem in other (context) menus. You could also enable color changes in settings app.

![menu](https://user-images.githubusercontent.com/16626308/49327347-cecce480-f560-11e8-8731-64d02be390e2.png)

You should also reorganize categories in menu, by alphabet or functionally. This could also be changed in settings.

Also, some apps (Welcome, Settings) still don't have icon.

**Comment by andersevenrud** [comment]
> Menu should be using a little different color to be separated with top panel.

Sure, that is doable.

> Also, some apps (Welcome, Settings) still don't have icon.

Not sure how you can sort if by functionality, but I'll make it sortable.

> Also, some apps (Welcome, Settings) still don't have icon.

Make sure to have the latest versions of npm packages installed. I was doing something in relation to this yesterday.

**Comment by andersevenrud** [comment]
This issue has been moved to https://github.com/os-js/osjs-panels/issues/9
