### ISSUE TITLE
Search window shows disabled scrollbar

### ISSUE THREAD

**Issue by filips123** [os-js/osjs-client#25]
Search window shows disabled scrollbar in Firefox. It is not displayed in Chrome.

![search](https://user-images.githubusercontent.com/16626308/49327449-39caeb00-f562-11e8-9515-fe9229758e3d.png)

Also, after search window is closed, previous app will not be returned to focus. Is this normal?

**Comment by andersevenrud** [comment]
> Also, after search window is closed, previous app will not be returned to focus. Is this normal?

This is normal, yes. But now that you mention it, the last window should get its focus back.

**Comment by filips123** [comment]
@andersevenrud What about this scrollbar? It should probably not be shown?

**Comment by andersevenrud** [comment]
That should not be visible when there's no results, so that's some compability thing that needs to be fixed in CSS.

**Comment by andersevenrud** [comment]
This has now been fixed and published in the latest `@osjs/client`.

**Comment by filips123** [comment]
Search window could show results in real time without pressing enter. Is this possible and good?

**Comment by andersevenrud** [comment]
That could be done if some sort of search indexing was added, probably.

Right now the searches are "raw", which is a bit too slow.
