### ISSUE TITLE
packages.running is undefined

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-client#29]
when I use `let packages = this.core.make('osjs/packages');` and I try to access `packages.running`, it returns `undefined` and this should be fixed.

**Comment by andersevenrud** [comment]
The Service Provider only exposes a small set of functions.

What are you trying to do ?

**Comment by SpaceboyRoss01** [comment]
Get a list of running packages.

**Comment by andersevenrud** [comment]
The `running` is just an array of strings. Is that enough ?

**Comment by SpaceboyRoss01** [comment]
Yes

**Comment by andersevenrud** [comment]
You can now use `this.core.make('osjs/packages').running()`.
