### ISSUE TITLE
In v2 I could set autostart and singular, v3 is missing those two

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-client#4]
In metadata.json I have:

  "singular": true,
  "autostart": true,

The package/app is not starting up when launching the server. I think there was a setting for turning of resizing of the window, can't seem to find that either, I did see win.setSize() functions though - maybe I looked in the wrong part of the new docs?

**Comment by andersevenrud** [comment]
I've updated https://manual.os-js.org/v3/tutorial/application/ with the now named `singleton` property that you can set in your metadata.

I can add support for `autostart` as well.

**Comment by andersevenrud** [comment]
Corrected a typo. Ops!

**Comment by andersevenrud** [comment]
From Gitter:

> In your `src/client/index.js` file:
>  osjs.on('osjs/core:started', () => osjs.run('MyApplication'));

This will autostart any application whenever OS.js has started.

**Comment by andersevenrud** [comment]
Oh, sorry. It's `osjs.launch()` not `.run()` :sweat_smile:

**Comment by andersevenrud** [comment]
I've published a new version of `@osjs/client` that adds support for the `autostart` metadata attribute.

Documentation has been updated as well.

Please note, for this update, you have to update `@osjs/panels` as well.

**Comment by aherreraGH** [comment]
Thank you, works well!
