### ISSUE TITLE
Personalizing notifications

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-client#47]
Being able to change the position where the notifications appear as well as possibly the color would be a nice touch.

**Comment by andersevenrud** [comment]
Indeed :+1:

**Comment by andersevenrud** [comment]
Where you thinking on a per-notification basis, globally, or both ?

**Comment by SpaceboyRoss01** [comment]
Both, more customization is better.12.01.2019, 13:39, "Anders Evenrud" <notifications@github.com>:Where you thinking on a per-notification basis, globally, or both ?

**Comment by andersevenrud** [comment]
OK.

Currently the notifications are added inside a preset container, but I guess this could be dynamically added if a position of the type string was given, ex `top-right` (just as `gravity` on windows work) -- then if it was an object with `{x, y}` it would not need a container and spawn statically.

Should be pretty trivial.

**Comment by andersevenrud** [comment]
It is now possible to configure styles (locally) and the position (globally). See referenced commits in this issue for more information.

This has been released in an update on npm.
