### ISSUE TITLE
Make window not resizable & hide header

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-client#5]
In my clocks app, the application is a static window on the screen. The user cannot resize it, move it, hide it, nor close it. 

In v3 (in v2 I did a similar thing) I added to my clocks css: 

```
.Window_WorldClocks > .osjs-window-inner > .osjs-window-header {
  display: none !important;
}
```
I think there ought to be a better way to do this. Give developers the ability to turn off window resizing, and also remove the header if they wish (removing the header can be separate from resizing, so it looks like a splash screen in a sense but the window is movable).

Perhaps in **metadata.json** file something like: 

```
"resizable" : true/false,
"show-header" : true/false
```

**Comment by andersevenrud** [comment]
You can define your window attributes when creating a window:

```
.createWindow({
  attributes: {
    resizable: false
  }
});
```

**Comment by andersevenrud** [comment]
I can add the header as an attribute as well (`header`) and maybe for the buttons as well (`controls`).

**Comment by andersevenrud** [comment]
https://manual.os-js.org/v3/api/osjs-client/typedef/index.html#static-typedef-WindowAttributes

**Comment by andersevenrud** [comment]
https://github.com/os-js/osjs-client/blob/master/src/window.js#L98

**Comment by aherreraGH** [comment]
ah. okay, and how about hiding the header?

**Comment by andersevenrud** [comment]
> ah. okay, and how about hiding the header?

https://github.com/os-js/osjs-client/issues/5#issuecomment-391460189

**Comment by aherreraGH** [comment]
Sorry, I typed that up and your other comments didn't show up until after I clicked "Comment" button heh

**Comment by andersevenrud** [comment]
Yeah, the issues don't sync up all the time when left open :)

**Comment by aherreraGH** [comment]
next time I'll reload the page before typing any comments 👍

**Comment by andersevenrud** [comment]
Just dawned on me that you can do it for example like this:

```
.render(($content, win) => {
  win.$header.style.display = 'none';
});
```

But an attribute is nicer ;)

**Comment by andersevenrud** [comment]
Please note that not all of these attributes are fully implemented (like `modal` and some of the `gravity`)

**Comment by andersevenrud** [comment]
I've published a new version of `@osjs/client` that now has two new attributes:

* `header`
* `controls`

Documentation has been updated as well.

Please note, for this update, you have to update `@osjs/panels` as well.
