### ISSUE TITLE
Support percentages as initial window dimension

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-client#56]
Add support for setting percentages as initial window dimensions.

This will not work when you start resizing stuff etc, so it would have to be reset to pixels when that occurs.

**Comment by SpaceboyRoss01** [comment]
Maybe having something like `20%-center` could subtract 20% from the center of the screen.

**Comment by andersevenrud** [comment]
@danialdanishazmi01 This will be added in the upcoming update.

You will be able to define a `float`, example: `0.5` is `50%`:

```javascript
.createWindow({
  title: 'Centered and using 50% of the screen space',
  position: 'center', // Just as an example, place window in the center
  dimension: {
    width: 0.5,
    height: 0.5
  }
})
```

I will do the same thing for `position: {left, top}` as well.

**Comment by andersevenrud** [comment]
This is now in the latest release. Also added `{attributes: {clamp: false}}` option to prevent windows being "pushed into viewport" if they go outside.

**Comment by andersevenrud** [comment]
@danialdanishazmi01 In case you're not following this issue, this is now supported in the latest release.

To update: https://manual.os-js.org/v3/install/#upgrade

Also updated the window tutorial to reflect this: https://manual.os-js.org/v3/tutorial/window/#attributes
