### ISSUE TITLE
Moving over to Rust.

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-client#67]
Using Rust and web assembly could vastly improve performance and have a greater impact on the possibilities of OS.js.

**Comment by andersevenrud** [comment]
But it also impacts development in so many other ways and browser support is not really up to par yet.
So, moving over to Rust is basically out of the question.

Using WASM for applications and integrations could be beneficial, like what I'm experimenting with the Xpra stuff but as for osjs-client, I don't really see the point.
