### ISSUE TITLE
Add a way to stop window destruction 

### ISSUE THREAD

**Issue by RianGallagher** [os-js/osjs-client#72]
At the moment there is no way to stop window destruction from happening after the user has tried to close a window. I think this would be a useful feature to have.

An example use case could be creating a confirmation dialogue when someone tries to close a window and only triggering destruction when they confirm.

**Comment by andersevenrud** [comment]
I'll add this when I'm home from work :)

**Comment by andersevenrud** [comment]
If you run `npm update @osjs/client` and rebuild with `npm run build`, you can now do the following when making a window:

```
.createWindow({
   ondestroy: () => {
     return false;
   }
})
```

The `return false` will block the destructor method. Any other value here is ignored and will make destruction work as usual.

**Comment by andersevenrud** [comment]
Since I haven't head back, I'm closing this issue. If you run into any issues, feel free to re-open :)

**Comment by RianGallagher** [comment]
@andersevenrud thanks for that, it works perfectly

**Comment by andersevenrud** [comment]
Glad to hear it! :)
