### ISSUE TITLE
Window resized event contains undefined parameters on mazimize/restore

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-client#77]
The resized event that fires after a window is maximized or minimized should contain the updated window dimensions. Currently the event parameters are undefined. Thanks my dude!

**Comment by andersevenrud** [comment]
Why do you need this for the `minimize` event ? The windows does not physically change dimensions at this point :thinking:

**Comment by josephjeno** [comment]
Ah right you are. Correction - the restore("un-maximize") event.

**Comment by andersevenrud** [comment]
Opened a PR for this that I'll deploy now: https://github.com/os-js/osjs-client/pull/78

**Comment by andersevenrud** [comment]
I published `@osjs/client@3.1.8` . Let me know how it works out :blush:

**Comment by josephjeno** [comment]
Works like a charm!

**Comment by andersevenrud** [comment]
Great!
