### ISSUE TITLE
Add setting in config.js to disable leftctrl to move

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-client#81]
We use leftctrl in some of our apps, which are conflicting with the osjs leftctrl behavior. Thanks!

**Comment by andersevenrud** [comment]
On it!

**Comment by andersevenrud** [comment]
PR incoming :)

https://github.com/os-js/osjs-client/pull/82

**Comment by andersevenrud** [comment]
I added this to the static global configuration for now, so you can do:

```
{
  windows: {
    matchKeyCombo: false
  }
}
```

I might change this in the future to apply to the user settings instead, but if that's the case I'll notify here (and leave backward compability for a while).

**Comment by andersevenrud** [comment]
Update should be out.

Run `npm update @osjs/client` and `npm run build` and let me know how it works out :)

**Comment by andersevenrud** [comment]
(in case you read notifications by email, I edited my second to last comment here about config, because I had a typo)

**Comment by josephjeno** [comment]
Works great, thanks Anders! @valp124 will be delighted.

**Comment by andersevenrud** [comment]
Glad to hear it :)
