### ISSUE TITLE
Add mountpoint filter based on user groups

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-client#83]
Currently it is possible to restrict access to mountpoints to particular user groups like below:

```
    mountpoints: [{
      name: 'shared',
      label: 'Shared',
      attributes: {
        root: path.resolve(root, 'vfs/shared'),
        groups: ['admin']
      }
     }]
```

And when a user in an unauthorized group tries to access it, they receive the below message:

![image](https://user-images.githubusercontent.com/29079278/69271353-accdd700-0ba2-11ea-9f1b-bd2d3914a1a9.png)

It would also be great if we could filter the mountpoints that appear, so the user only sees those that they have access to. That would prevent instances where there are large numbers of mountpoints, but the user only has access to one or two.

**Comment by andersevenrud** [comment]
On it! :)

**Comment by andersevenrud** [comment]
This should take care of it: https://github.com/os-js/osjs-client/pull/84

Merging and releasing asap

**Comment by andersevenrud** [comment]
`@osjs/client@3.1.0` is now out. Get it while it's hot :)

This change will now kick in when you add `groups: []` to a mountpoint on the *client*.

**Comment by andersevenrud** [comment]
>     mountpoints: [{
>       name: 'shared',
>       label: 'Shared',
>       attributes: {
>         root: path.resolve(root, 'vfs/shared'),
>         groups: ['admin']
>       }
>      }]

Note that the `groups` property is on the root object, not inside `attributes` :)

**Comment by andersevenrud** [comment]
Hold on. I think I might be wrong about my previous comment :man_facepalming:

**Comment by josephjeno** [comment]
awesome my dude, thanks very much! Excited to try this out.

**Comment by andersevenrud** [comment]
Yeah. I read it wrong on my end. Fixing that now :laughing:

**Comment by andersevenrud** [comment]
Okay. 3.1.11 is now out that makes the client-side configuration the same as server-side (i.e. `groups` is under `attributes`).

**Comment by josephjeno** [comment]
works perfectly
