### ISSUE TITLE
User group checking is too strict

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-client#85]
Currently if an application (or mountpoint) has multiple groups, ie ["admin", "webce"], the user must be a member of both groups in order for the application to be visible.  I think the application should be visible if a user is a member of any one of the application groups.

**Comment by andersevenrud** [comment]
PR incoming: https://github.com/os-js/osjs-client/pull/86

**Comment by andersevenrud** [comment]
3.1.12 has now been released with these changes.

The following settings should resolve your issue:
```
{
  attributes: {
    strictGroups: false
  }
}
```

**Comment by josephjeno** [comment]
Thanks Anders, just checking that will also work if I plop it into the application metadata.json? Or only vfs mountpoints?

**Comment by andersevenrud** [comment]
VFS Mountpoints only.

**Comment by josephjeno** [comment]
Ah I see, is it possible to have a similar solution for applications? It exhibits the same strict group behavior by default as the vfs mountpoints.

**Comment by andersevenrud** [comment]
Looking at that now :)

**Comment by andersevenrud** [comment]
3.1.13 is now out, which supports the same property inside `metadata.json` :)

**Comment by andersevenrud** [comment]
(without the `attributes` ofc. Just straight into the root JSON object)

**Comment by andersevenrud** [comment]
Since you reported it works fine on the Gitter chat I'll be closing this one. Thanks!
