### ISSUE TITLE
save session not working when window is maximized and saved

### ISSUE THREAD

**Issue by santhoshR-Dev** [os-js/osjs-client#99]
this.core.make('osjs/session').save();     is not working when we maximes the window and save the session. it is saving the previous width and height before maximizing the window.

![Screenshot (96)](https://user-images.githubusercontent.com/61528245/75406945-d1db8f80-58df-11ea-8843-d7f4e4b3bac0.png)
![Screenshot (95)](https://user-images.githubusercontent.com/61528245/75406963-db64f780-58df-11ea-9aaf-5bc223cc7fe7.png)

**Comment by andersevenrud** [comment]
Hi,

Indeed. It seems like the maximized state does not affect session restoration.

I'll have a look into it.

Thanks!

**Comment by andersevenrud** [comment]
Coming up ASAP in the following PR

https://github.com/os-js/osjs-client/pull/100

**Comment by andersevenrud** [comment]
This has been fixed and released in the latest version of `@osjs/client`.

The demo site will be updated as well.
